### ISSUE TITLE
Human readable key stored

### ISSUE THREAD

**Issue by DjayDev** [dlemmermann/PreferencesFX#14]
Hi,

When a key is stored (except one of the predefined for positions and size), the key is a sha-256 converted to String.
When you look in the registry (in Windows), you have this uggly look:
![image](https://user-images.githubusercontent.com/7959058/40979008-e2ce4a8c-68d4-11e8-90ad-73334ccc00b7.png)

I see that you want to use a hash of the key given, but
1. you don't apply this rule to your keys, so why the other should do?
2. why not store the breadcrumb directly?

And remember:
“Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.” – John F. Woods
which is also available for the results of the code.

**Comment by martinfrancois** [comment]
Hi @DjayDev 
Thanks for your comment 👍. Like I mentioned in #15, the reasoning behind this is explained in the JavaDoc of `StorageHandler#hash(String)`.

I agree this is not a very pretty solution, but it's the best approach we found that would allow to save indefinitely long breadcrumbs to the preferences and thus circumvent the limits of the 80 character key length limitation as posed by the Java Preferences API... I respect Joshua Bloch (the author of the Java Preferences API) and I am pretty sure he had his reasons for imposing this limit, although to be fair he didn't document them anywhere as far as I could see.

If you have a suggestion for an implementation, which guarantees having keys with a length of less than 80 characters for indefinitely long breadcrumbs which remain human-readable, we would be glad hearing about it.

Thanks!

**Comment by DjayDev** [comment]
Not ideal, but the first idea that comes would be to have an hybrid solution: when the breadcrumb is less than 80char, we leave it clear and for breadcrumbs more than 80 chars, we would use the hash (and a pref to use always the hash like it is now so it won't break the current implementation).
Based on your experience, do you think the breadcrumbs is often higher than 80 chars?
If you're ok with such workaround, I could have a look. Let me know what you think.

**Comment by martinfrancois** [comment]
I think this approach could work, I just don't see the benefit of having all of this additional code (potentially resulting in bugs and making it harder to maintain) to just have some of the keys in human-readable form. I don't think most people will have a look at the registry to change the values, or is there a certain use case that you have in mind, where it would be useful to have the keys stored in human-readable form?

**Comment by DjayDev** [comment]
The use case is to be used with the listener like I showed in the samples I submitted. I know I should be able to do it with the hash function (not tested but I guess) but it's more convenient to do it with readable preferences.
It's a way to read and/or change the preferences outside the dialog like it was asked in the question #8

**Comment by martinfrancois** [comment]
I see what you mean @DjayDev. To have a listener for the changed settings I think it makes more sense to apply a listener to the property itself that you define in the appropriate spot where you need it in your application and to react to it there. If you just generally want an information for debugging to see the changed settings, I think the approach I proposed in #15 with logging would make sense.
As for #8, I think it makes more sense to fix this problem at its root than to go with a workaround like this. For example, we could save the preferences when they change externally with a listener in PreferencesFX itself, which would be a quite easy and clean solution in my opinion.

If there is any other use case you know of where this would be benefitial, feel free to let me know!

**Comment by martinfrancois** [comment]
Since there was no response, I will close this issue. Feel free to open it up again or create another issue should you still run into issues.
