### ISSUE TITLE
Integer editor allows non numeric characters

### ISSUE THREAD

**Issue by aalmiray** [dlemmermann/PreferencesFX#27]
It's possible for users to type in non numeric characters (such as letters) in the default renderer of an `IntegerProperty`. This leads to exceptions being thrown when using the up/down arrows or storing properties.

**Comment by martinfrancois** [comment]
Hi @aalmiray 
Thanks for submitting that issue! That is indeed a bug. Feel free to submit a PR fixing this issue!

**Comment by martinfrancois** [comment]
Fixed by #41
