### ISSUE TITLE
Retreive Saved prefrences with out binding

### ISSUE THREAD

**Issue by abdoFX** [dlemmermann/PreferencesFX#34]
Hi, 
I want to know, how to retreive saved prefrences , PrefrencesFX Object
Some thing like  
if(prefs.get("settingName") == "some thing") {

// do task
}

Thank's in advenced,

**Comment by martinfrancois** [comment]
Hi @abdoFX,

In your application, simply declare a property:
`StringProperty welcomeText = new SimpleStringProperty("Hello World");`
Then, create a `PreferencesFx` object, using that property in a setting:
```
PreferencesFx preferences = PreferencesFx.of(AppStarter.class,
        Category.of("General",
            Setting.of("Welcome Text", welcomeText)
        )
);
```
Now you can show the preferences dialog by calling:
`preferences.show()`

If you now want to retrieve the saved preferences (here for example, what string has been entered in `welcomeText`), you simply use:
**`welcomeText.get()`**

In your example, you could use:
```
if(welcomeText.get().equals("hello") {
  // do task
}
```

I hope that helps!

**Comment by martinfrancois** [comment]
Since there was no response, I will close this issue. Feel free to open it up again or create another issue should you still run into issues.

**Comment by qq1053831109** [comment]
PreferencesFx.of need after javafx start! but i need in main code use Preferences
