### ISSUE TITLE
Allow preferences to be saved at any time

### ISSUE THREAD

**Issue by aalmiray** [dlemmermann/PreferencesFX#35]
Currently preferences may be saved after the dialog is closed. It would be great to allow preferences to be saved at any point in time without having to pop open the dialog, think for example an application that stores `x`, `y`, `width`, `height` coordinates of the main window. These coordinates may be set using the preferences dialog, but can also be updated by tracking user actions (such as resizing or dragging the window). These values should be stored before the application is shutdown.

There are at least 2 possible options with the current API design:
 
 1. add a getter to expose `PreferencesModel`.
 2. add an explicit method to `PreferencesFX` such as  `savePreferences`.

Personally I'd lean for option 1 as you may also load/sync preference values at any time value calling `load` on the model. This still keeps the load/save behavior in one place: the model.

Related to #8

**Comment by martinfrancois** [comment]
Implemented with #36
