### ISSUE TITLE
Replace StorageHandler

### ISSUE THREAD

**Issue by tobiasdiez** [dlemmermann/PreferencesFX#4]
What is the preferred way to replace the built-in [StorageHandler](https://github.com/dlemmermann/PreferencesFX/blob/develop/src/main/java/com/dlsc/preferencesfx/util/StorageHandler.java) by a custom implementation? This seems to be necessary if one wants to save the preferences not using the Java Preference API (e.g. store the preferences in a file instead).

**Comment by Genron** [comment]
Hello @tobiasdiez 
Currently the replacement of the `StorageHandler` is not supported, but feel free to implement it on your own and make a pull request.

You can then listen at the properties you defined and save the preferences manually as they change.

Changing the usage of the `StorageHandler` can be achieved using following methods:

| Method | Behaviour |
|----------|:------------|
| `persistApplicationState` | The `Preference API` is not used at all. |
| `persistWindowState` | Decides wether to store the position and size of the preferences window or not |
| `saveSettings` | Enables / disables the storing of the preferences values |

**Comment by kivimango** [comment]
I second that.I need a custom implementation of StorageHandler (like Spring Scurity's UserDetailsService) because in my app there is a separate service object for loading and saving the app's config properties.Sometime i will make the change and create the PR.Anyway great lib.

**Comment by martinfrancois** [comment]
@kivimango thanks a lot for the feedback, that's great to hear! 😄
