### ISSUE TITLE
load

### ISSUE THREAD

**Issue by jmendezv** [dlemmermann/PreferencesFX#44]
Why are preferences encrypted?

**Comment by martinfrancois** [comment]
Hi @jmendezv 

The preferences are not encrypted. The keys under which they are stored however are indeed **hashed**. You can find the reason for that in `StorageHandlerImpl.java`, in the javadoc of the `hash()` method:
```
  /**
   * Generates a SHA-256 hash of a String.
   * Since {@link Preferences#MAX_KEY_LENGTH} is 80, if the breadcrumb is over 80 characters, it
   * will lead to an exception while saving. This method generates a SHA-256 hash of the breadcrumb
   * to save / load as the key in {@link Preferences}, since those are guaranteed to be
   * maximum 64 chars long.
   *
   * @return SHA-256 representation of breadcrumb
   */
```

**Comment by jmendezv** [comment]
Ok, I get it, you just want to guaranteed a decent keysize.

**Comment by martinfrancois** [comment]
It's not really that we want, it's more that if we have a key that is longer than 80 characters, the Java Preferences API will throw an exception during saving and that of course is not acceptable ;-)
