### ISSUE TITLE
Missing legend with quicklinks in the ReadMe.

### ISSUE THREAD

**Issue by Naoghuman** [dlemmermann/PreferencesFX#48]
Missing legend with quicklinks in the ReadMe.

In your amazing ReadMe I missing after the start section the `legend` with the quicklinks in the ReadMe which allowed the interested to jump quickly the section from interest.

Have a look in the ReadMe from https://github.com/openjfx/samples after the section 'Description'. When you want I can create a PR.

**Comment by martinfrancois** [comment]
Hi @Naoghuman

Thanks for the suggestion!
In fact, over at https://github.com/dlemmermann/WorkbenchFX we do have a table of contents. Feel free to implement it and submit a PR.

Thanks!
François

**Comment by martinfrancois** [comment]
Merged PR #49.
