### ISSUE TITLE
How to access single preference values

### ISSUE THREAD

**Issue by tobiasdiez** [dlemmermann/PreferencesFX#5]
Thanks for creating such a nice library. I like the idea and realization looks really promising.

There is one thing I couldn't figure out while browsing through the code. I hope it is ok if I use this issue tracker for my question: How do I load and save single (or multiple) settings without using the preference dialog?

The structure in the examples appears to be: you create a `PreferencesFx` instance which specifies in which categories and groups you want to display your settings. The preferences values are synced with JavaFX properties. I can then bind these properties to my controls or read their current values depending on my needs.
My questions with this process are the following:
- Which method actually loads the preference values from the `StorageHandler` into these JavaFX properties.
- Are the properties synced with the preference store, i.e. can I just change a value of the property and it is automatically stored in the registry?
- What is the preferred way to access the current value of a given preference, especially if I want to respect separation between gui and backend code. Thus I probably don't want to use the `PreferencesFX` class because this is used to show the dialog, i.e. it GUI code. 

So these questions can kind of be summarized in: How do you structure preferences loading and saving with your library while respecting separation of gui and backend logic?

**Comment by Genron** [comment]
Hello @tobiasdiez 

Thanks for your feedback. We appreciate it a lot.
The preferences dialog opens only when you call the method `yourPreferences.show();`. So the best way for using the PreferencesFX would be:
- Initiate the `Properties` you use in your application
- Create the `PreferencesFX Object` with those properties
--> Without calling `.show();` your properties are now bound to the `PreferencesFX Object` and are updated with the current value.

You can use now your properties in your application. To change the preferences, you can open the Dialog using the `.show();` method and make your changes.

Considering your questions:
- Q1: The Class `PreferencesFxDialog` loads the preferences and window states when opening the `Dialog` and stores them when closing it. You can find the method for this in the class `PreferencesFxModel`, with the name `saveSettingValues` and `loadSettingValues`. To see where the methods are being called, use the functionality of your preferred IDE to do so.
- Q2: Yes, the properties you define are bound at the `PreferencesFx Object`. When you change the data in the Dialog, the properties are automatically updated. But if you change the properties manually outside the preferences dialog, they are automatically synced in PreferencesFX, but they will only be saved if the dialog is opened and then closed again. We thought this was the best compromise in terms of performance - but if you have a use case for such a scenario we could consider to change this behavior.
- Q3: You can listen to the properties you define when creating the preferences. They are bound at the PreferencesFx Object and change automatically when you change the values in the Dialog. 

We hope, your questions are answered properly, but if we missed your point feel free to ask again.

**Comment by martinfrancois** [comment]
Since there has not been any reaction by @tobiasdiez yet, I'll close this issue. Feel free to reach out though, if you still have any questions! 😃
