### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by ArvidNy** [dlemmermann/PreferencesFX#51]
I was just wondering if you plan on supporting icons for the tree items? Something like this:

![treeviewicons](https://docs.oracle.com/javafx/2/ui_controls/img/tree-view-hr1.png)

I am investigating the possibility use your library instead of our own settings dialog with tabs, and being able to use the same icons would ease the transition for the users.

![options](https://user-images.githubusercontent.com/14236185/50920580-096e4a80-1446-11e9-9067-6390d7235aad.png)

On a side note (you can make this a separate issue if you would consider this a feature suggestion), I'm also wondering if you plan on allowing users to add custom nodes (mainly images) to a category? As you can see in the example above, we use images to help users know what they are changing.

**Comment by martinfrancois** [comment]
I think the idea of both sounds great. The first one should be quite easy to do, as `TreeItem` already supports adding icons, so it would be more a matter of extending the API and setting the icons for each category. Feel free to submit a PR!

**Comment by ArvidNy** [comment]
Sure, I could submit a PR for this issue. I took a quick look and, as you said, it was quite easy to add. 

As for the other one, I started looking at that one as well and I did manage to pass a node to a group (simplified: `Group.of(groupName, Setting.of("Output:", resolutionItems, resolutionSelection)).addGroupNode(new ImageView(new Image(image))` -> _Group.java_ `preferencesGroup.setGroupNode(node);` -> _PreferencesFxGroupRenderer.java_ `grid.add(preferencesGroup.getGroupNode(), columnBase++, nextRow, 1, 2);`) which resulted in the output below. Needless to say, the image could be placed anywhere else in the group as well.

![custom views](https://user-images.githubusercontent.com/14236185/51072631-326c2680-1664-11e9-9b71-0498456b31c6.png)

If it would be of interest, I could submit a PR for that as well. However, this approach is probably only good if you just want to add something to the side of the group, like I've done here, or above/below it. In case you'd want to add another custom item that should go somewhere between the items (e.g. a ColorPicker or a Button that we have in our existing dialog), the code quickly gets quite messy as you try to determine which position in the group it should have. For that, I guess that the best approach would probably be to add classes like CustomField and CustomProperty that would allow the user to pass the node in the Setting.of() method instead, but I didn't feel I have the time to dig further into it and will leave it at that - so feel free to pick that up if you would be interested.

**Comment by ArvidNy** [comment]
In case anybody else would be interested in adding custom preferences, I took another look at it and realized I could extend the SimpleControl class and add any nodes I wanted, even though there wasn't a proper Field for it yet. Until it's officially supported, I've created a ColorPicker preference and a DirectorySelector preference. Just contact me in case you'd need help getting going with this.

**Comment by martinfrancois** [comment]
Yes, you correctly understood that you could use a custom field for that.
Feel free to submit a PR including a custom color picker control and directory selector, I think they would make great additions!

Regarding the image, maybe we could think about adding icon support to groups as well as we did now with categories? I don't know if the large image below a group name would be appropriate for a lot of projects, but I think placing an icon on the left of the group name in a similar way to how it's done in the `TreeView` currently should be okay?
Maybe @Genron you have an idea as to what would make most sense here?

**Comment by ArvidNy** [comment]
Sure, I'll try to make a PR for those as well.

You might be right that perhaps there's not many projects apart from us that would want that kind of images. In this scenario, we might as well set the images as smaller group icons (similar to the TreeItem icons), but we also would like to add a QR image to one of the tabs where it wouldn't be ideal to have it that small. Right now, I've solved it by making a custom item and add the item next to the setting, but the alignment doesn't look that good. I don't want to add it as a new setting item (that would return an empty value), but that could be another approach for that. For us, being able to place an image next to a group (or even next to a single setting) would be good, but perhaps we're rather alone in that.

**Comment by martinfrancois** [comment]
Implemented in #52
