### ISSUE TITLE
Use as Node

### ISSUE THREAD

**Issue by Xerus2000** [dlemmermann/PreferencesFX#6]
Can I also have the preferences as Node, for example to make it a tab? Or does it only support popup dialogues?

**Comment by jchildress** [comment]
I'd be a fan of the requested functionality...

**Comment by Xerus2000** [comment]
Any progress? This is a major blocker since I can only utilise this when I can embed it into a the application window. Shouldn't even be hard, just return the Component that's in the Window?

**Comment by martinfrancois** [comment]
Implemented in #36
