### ISSUE TITLE
File/Directory setting type with chooser?

### ISSUE THREAD

**Issue by integratedmodelling** [dlemmermann/PreferencesFX#65]
I'd love to use PreferenceFX but I'm held back by the lack of a setting that would allow the user to pick an existing or new file/directory from the file system. Seems to be a pretty general-purpose setting and I'm surprised it's not been asked about. Is there any plan to add that, or any easy workarounds that I've missed? I may eventually put some resources towards implementing it myself, but that's very unlikely for the time being.

**Comment by ArvidNy** [comment]
You might want to take a look at [this PR](https://github.com/dlemmermann/PreferencesFX/pull/62) where I've made a simple directory chooser. Ideally this should be implemented in a better way in the future, but this works without any changes to the library. It should also give you an idea of how to make other custom preferences if you find anything else that's missing.

**Comment by jeacott1** [comment]
I have a similar issue for lack of a font/size/style chooser

**Comment by ArvidNy** [comment]
@jeacott1, can't you just use a combobox for setting the font and style and a integer/double range for the font size? We load the system fonts for our project into combobox [like this](https://github.com/quelea-projection/Quelea/blob/e3801feef989c5a620c74d1511422e9998355c98/Quelea/src/main/java/org/quelea/windows/options/PreferencesDialog.java#L131-L132), using [this code](https://github.com/quelea-projection/Quelea/blob/e3801feef989c5a620c74d1511422e9998355c98/Quelea/src/main/java/org/quelea/services/utils/Utils.java#L904-L916) to retrieve the fonts as an array. I wouldn't say you'd need a new kind of preference for that.

**Comment by martinfrancois** [comment]
Implemented in #67

**Comment by martinfrancois** [comment]
Hi @integratedmodelling @ArvidNy @jeacott1 
The fix for this issue was included in release `8.3.0` (for Java 8) and `11.3.0` (for Java 11), which has just been released.
