### ISSUE TITLE
How to Wrap root with another parent?

### ISSUE THREAD

**Issue by aang7** [dlemmermann/PreferencesFX#66]
Hi Just a question, is there a way to wrap the preferencefx window content into another Node?
I just want to wrap all the content in a stackpane... thank you.

**Comment by martinfrancois** [comment]
Hi,
Yes that's possible. Check the "node" demo to see how it works: https://github.com/dlemmermann/PreferencesFX/tree/develop/preferencesfx-demo/src/main/java/com/dlsc/preferencesfx/node
You can also clone this repository and run the demo application to see it in action.
Hope that helps!
