### ISSUE TITLE
Add possibillity to make Dialog APPLICATION_MODAL

### ISSUE THREAD

**Issue by finanzer** [dlemmermann/PreferencesFX#7]
Now it's not possible to set a init owner and the Dialog is not application modal. And there is no possibility to change this. This results in a new window without an icon and parallel using of application and preferences dialog (see screenshot). 

![image](https://user-images.githubusercontent.com/10505961/40173589-a2b3e4fe-59d2-11e8-97b4-4b390894c943.png)

It would be better, if this could be configured.

**Comment by martinfrancois** [comment]
I agree. This is a useful addition.

**Comment by martinfrancois** [comment]
Closing, since it's covered in #12

**Comment by aalmiray** [comment]
Any news regarding the next release?

**Comment by dlemmermann** [comment]
I announced it on Twitter. You said "Thank you!" :-)

**Comment by aalmiray** [comment]
Indeed, however version `2.0.1` does not include this change as `2.0.1` was released on April 30th, but the fix was merged in June 18th.

**Comment by dlemmermann** [comment]
Oh wait ... wrong project :-) I was thinking of FormsFX ..... stupid me.

**Comment by aalmiray** [comment]
Too many projects to juggle around 😏

**Comment by dlemmermann** [comment]
Version 2.0.2 is now pushed to jcenter and maven central. Might take an hour or so to actually appear / be accessible.

**Comment by aalmiray** [comment]
Great! This will get me closer to what I need however a solution to #20 would be better IMHO.

Thanks again! 😄
