### ISSUE TITLE
Subcategories not displayed when only one main category

### ISSUE THREAD

**Issue by p1r9t3** [dlemmermann/PreferencesFX#72]
When creating the menus, if there is only one main category with a sub-category... it just displays as a single settings window with no option to open the sub-category.

**Comment by p1r9t3** [comment]
Submitted pull request to fix this issue.

**Comment by martinfrancois** [comment]
Fixed in #76

**Comment by martinfrancois** [comment]
Hi @p1r9t3 
The fix for this issue was included in release `8.3.0` (for Java 8) and `11.3.0` (for Java 11), which has just been released.
