### ISSUE TITLE
Too many Dependencies

### ISSUE THREAD

**Issue by sclassen** [dlemmermann/PreferencesFX#78]
PreferencesFX has many dependencies which themselves bring more transitive dependencies.
For a library which will be used in other projects this is sub optimal as it can easily lead to dependency hell.
For example: currently PreferencesFX has two versions of guava as its dependencies (27.0.1-jre and a shaded 21.0.0)

![dependencies](https://user-images.githubusercontent.com/1795224/61156728-64b3ef00-a4f4-11e9-8d9b-3925845624ba.png)

I can provide a PR to decrease the number of dependencies if you see this as decirable

**Comment by martinfrancois** [comment]
Hi Stephan,
Sure, feel free to submit a PR for that, as long as we don't break any licenses in the process 😉 
But I think for sure the shaded dependency on Guava 21.0.0 is something that would make sense and is doable without much effort.

**Comment by martinfrancois** [comment]
Closing since #79 was merged.
