### ISSUE TITLE
NPE in SimpleRadioButtonControl

### ISSUE THREAD

**Issue by finanzer** [dlemmermann/PreferencesFX#9]
SimpleRadioButtonControl in not working because the order in initializeParts() is wrong the correct Code would be 

`    
public void initializeParts() {
        super.initializeParts();

        node = new HBox();
        node.getStyleClass().add("simple-radio-control");

        toggleGroup = new ToggleGroup();

        createRadioButtons();
    }
`
The assignment to fieldLabel is removed, because this field is useless.

**Comment by martinfrancois** [comment]
Hi @finanzer 

Thanks a lot for your issue!

You're absolutely right! I also noticed the same issue is true for "SimpleCheckBoxControl", "SimpleBooleanControl". Please submit a PR and we will happily merge it!

**Comment by martinfrancois** [comment]
Fixed in #16, thanks again @finanzer!
